from __future__ import annotations
from typing import Protocol
from .types import (BackendOperationResult, PreparedOutput, PreparedReputation, ReconstructionResult,
                    ShareBundle, TranscriptBundle)

class MPCBackend(Protocol):
    backend_kind: str
    profile: object
    def share_secret(self, secret_id: str, value: int, *, namespace: str = "share") -> ShareBundle: ...
    def reconstruct(self, bundle: ShareBundle) -> ReconstructionResult: ...
    def local_add(self, left: ShareBundle, right: ShareBundle) -> BackendOperationResult: ...
    def local_sub(self, left: ShareBundle, right: ShareBundle) -> BackendOperationResult: ...
    def SecSqr(self, value: ShareBundle) -> BackendOperationResult: ...
    def SecMulPositive(self, left: ShareBundle, right: ShareBundle) -> BackendOperationResult: ...
    def PubMulPositive(self, value: ShareBundle, coefficient: int) -> BackendOperationResult: ...
    def SecDivPositive(self, numerator: ShareBundle, denominator: ShareBundle, lower: int, upper: int) -> BackendOperationResult: ...
    def refresh(self, bundle: ShareBundle, *, namespace: str) -> ShareBundle: ...
    def prepare_output(self, task_id: str, output: ShareBundle, q_out_recomputed: bool) -> PreparedOutput: ...
    def prepare_reputation(self, worker_id: str, previous_epoch: int, next_epoch: int, update_count: int = 1) -> PreparedReputation: ...
    def export_transcript(self, *, public: bool = True) -> TranscriptBundle: ...
