from __future__ import annotations
from dataclasses import dataclass
from enum import StrEnum
from fractions import Fraction
from .encoding import rational,trunc_scaled
from .profile import FixedBackendProfile
from ..core.consistency_scale import squared_distance_bound_from_modality
class PreflightStatus(StrEnum):PASSED='passed';REJECTED='rejected';UNRESOLVED='unresolved'
@dataclass(frozen=True)
class RangeEntry:
 entry_id:str;operation:str;semantic_quantity:str;derivation_formula:str;dependencies:tuple[str,...];assumptions:tuple[str,...];iteration_scope:str;participant_scope:str;coordinate_scope:str;semantic_lower_bound:str;semantic_upper_bound:str;encoded_lower_bound:int;encoded_upper_bound:int;maximum_absolute_integer:int;modulus_limit:int;safety_margin:int;no_wrap_status:str;denominator_status:str;coefficient_retention_status:str;error_bound_status:str;source_reference:str;reason_code:str|None=None
@dataclass(frozen=True)
class StaticPreflightCertificate:
 preflight_status:PreflightStatus;backend_profile_hash:str;reason_code:str|None;maximum_intermediate_integer:int;p_safety_margin:int;no_wrap_status:str;denominator_status:str;coefficient_retention_status:str;error_bound_status:str;public_bounds:dict[str,int];source_references:tuple[str,...];range_entries:tuple[RangeEntry,...]=()
def derive_entries(p:FixedBackendProfile,N:int,D:int,epsilon:Fraction,tau:Fraction,eta:Fraction,kappa:Fraction,report_upper:Fraction=Fraction(1),reputation_upper:Fraction=Fraction(1),task_kind:str='numerical')->tuple[RangeEntry,...]:
 delta=p.scale_delta;limit=(p.prime_p-1)//2
 beta=(1-eta*kappa,eta,eta*(kappa-1));diff=report_upper; sq=diff*diff;distance_geometry=squared_distance_bound_from_modality(task_kind,D);dist=distance_geometry*sq;qden=tau+dist;qmax=Fraction(1);emax=reputation_upper+epsilon;inf=emax*qmax;isum=N*inf;num=N*inf*report_upper;cq=reputation_upper*qmax;terms=(beta[0]*reputation_upper,beta[1]*qmax,beta[2]*cq);rep=sum(terms);spec=[
 ('report_encoding','encode report','report','report_upper',['report domain']),('reputation_encoding','encode reputation','reputation','reputation_upper',['reputation domain']),('epsilon_c','encode epsilon','epsilon_c','epsilon_c',['epsilon_c']),('tau','encode tau','tau','tau',['tau']),('eta','encode eta','eta','eta',['eta']),('kappa','public kappa','kappa','kappa',['kappa']),('beta0','quantize 1-eta*kappa','beta0','1-eta*kappa',['eta','kappa']),('beta1','quantize eta','beta1','eta',['eta']),('beta2','quantize eta*(kappa-1)','beta2','eta*(kappa-1)',['eta','kappa']),('report_difference','report-truth','difference','report_upper',['report_encoding','aggregate_truth']),('coordinate_square','difference squared','square','diff_upper^2',['report_difference']),('dimension_distance_sum','sum coordinate squares','distance','diam2*square_upper',['coordinate_square','domain_geometry']),('tau_plus_distance','tau+distance','tau_distance','tau+distance_upper',['tau','dimension_distance_sum']),('q_denominator','positive q denominator','q_denominator','tau+distance_upper',['tau_plus_distance']),('q_output','tau/(tau+d)','q','1',['q_denominator','tau']),('influence','(c+epsilon)*q','influence','(reputation_upper+epsilon)*q_upper',['reputation_encoding','epsilon_c','q_output']),('minimum_positive_influence','epsilon*q_lower','min influence','epsilon*tau/(tau+distance_upper)',['epsilon_c','q_denominator']),('influence_sum_denominator','sum N influences','influence sum','N*influence_upper',['influence','N']),('aggregate_numerator','sum influence*report','aggregate numerator','N*influence_upper*report_upper',['influence','report_encoding','N']),('aggregate_denominator','sum influences','aggregate denominator','N*influence_upper',['influence_sum_denominator']),('aggregate_truth','numerator/denominator','truth','report_upper',['aggregate_numerator','aggregate_denominator']),('d_out','final squared distance','d_out','diam2*square_upper',['coordinate_square','domain_geometry']),('q_out','tau/(tau+d_out)','q_out','1',['d_out','tau']),('c_times_q','c*q','c*q','reputation_upper*q_upper',['reputation_encoding','q_out']),('reputation_beta0_term','beta0*c','beta0 term','beta0*reputation_upper',['beta0','reputation_encoding']),('reputation_beta1_term','beta1*q','beta1 term','beta1*q_upper',['beta1','q_out']),('reputation_beta2_term','beta2*c*q','beta2 term','beta2*cq_upper',['beta2','c_times_q']),('reputation_candidate_sum','sum reputation terms','candidate','sum(term bounds)',['reputation_beta0_term','reputation_beta1_term','reputation_beta2_term']),('canonical_modulo_representation','z mod p','canonical representative','p-1',['p']),('balanced_representation','Bal_p(z)','balanced representative','(p-1)/2',['p']),]
 vals={'report_upper':report_upper,'reputation_upper':reputation_upper,'epsilon_c':epsilon,'tau':tau,'eta':eta,'kappa':kappa,'1-eta*kappa':beta[0],'eta*(kappa-1)':beta[2],'diff_upper^2':sq,'diam2*square_upper':dist,'tau+distance_upper':qden,'1':qmax,'(reputation_upper+epsilon)*q_upper':inf,'epsilon*tau/(tau+distance_upper)':epsilon*tau/(tau+dist),'N*influence_upper':isum,'N*influence_upper*report_upper':num,'reputation_upper*q_upper':cq,'beta0*reputation_upper':terms[0],'beta1*q_upper':terms[1],'beta2*cq_upper':terms[2],'sum(term bounds)':rep,'p-1':Fraction(p.prime_p-1),'(p-1)/2':Fraction(limit)}
 out=[]
 for eid,op,quantity,key,deps in spec:
  upper=vals[key];enc=(upper*delta).numerator//(upper*delta).denominator
  if eid=='canonical_modulo_representation':enc=p.prime_p-1
  maxi=enc;out.append(RangeEntry(eid,op,quantity,key,tuple(deps),('public domains only',),'all K' if eid not in {'report_encoding'} else 'input','all N','all D',str(0),str(upper),0,enc,maxi,limit,limit-maxi,'passed','passed','passed','passed','eq:implementation-parameter-preflight;eq:modulus-preflight'))
 full=max(x.maximum_absolute_integer for x in out if x.entry_id not in {'canonical_modulo_representation','balanced_representation'});out.append(RangeEntry('full_flow_maximum','max certified intermediates','full flow maximum','max(dependent entry maxima)',tuple(x.entry_id for x in out),'public domains only', 'all K','all N','all D','0',str(Fraction(full,delta)),0,full,full,limit,limit-full,'passed' if full<=limit else 'rejected','passed','passed','passed','eq:explicit-app-bound;eq:modulus-preflight'))
 return tuple(out)
def preflight(profile:FixedBackendProfile,*,participants:int,dimension:int,K:int,epsilon_c:object,tau:object,eta:object,kappa:object,report_upper:object='1',reputation_upper:object='1',task_kind:str='numerical')->StaticPreflightCertificate:
 try:
  e,t,et,k,ru,cu=map(rational,(epsilon_c,tau,eta,kappa,report_upper,reputation_upper))
  if participants<1 or dimension<1 or K<1:raise ValueError('INVALID_PUBLIC_SHAPE')
  if e<Fraction(1,profile.scale_delta) or t<Fraction(1,profile.scale_delta):raise ValueError('DENOMINATOR_BELOW_BOUND')
  if et<=0 or k<1 or et>1/k:raise ValueError('INVALID_REPUTATION_PARAMETERS')
  beta=(1-et*k,et,et*(k-1))
  if any(x>0 and trunc_scaled(x,profile.scale_delta)==0 for x in beta):raise ValueError('COEFFICIENT_QUANTIZED_ZERO')
  entries=derive_entries(profile,participants,dimension,e,t,et,k,ru,cu,task_kind);maximum=next(x.maximum_absolute_integer for x in entries if x.entry_id=='full_flow_maximum');limit=(profile.prime_p-1)//2
  if maximum>limit:raise ValueError('NO_WRAP_VIOLATION')
  return StaticPreflightCertificate(PreflightStatus.PASSED,str(profile.digest()),None,maximum,limit-maximum,'passed','passed','passed','passed',{'participants':participants,'dimension':dimension,'K':K,'task_kind':task_kind,'squared_distance_bound':str(squared_distance_bound_from_modality(task_kind,dimension))},('eq:implementation-parameter-preflight','eq:modulus-preflight'),entries)
 except Exception as exc:
  reason=str(exc) or 'UNRESOLVED_PUBLIC_BOUND';return StaticPreflightCertificate(PreflightStatus.REJECTED,str(profile.digest()),reason,0,(profile.prime_p-1)//2,'rejected','rejected','rejected' if reason=='COEFFICIENT_QUANTIZED_ZERO' else 'passed','unresolved',{'participants':participants,'dimension':dimension,'K':K,'task_kind':task_kind,'squared_distance_bound':str(squared_distance_bound_from_modality(task_kind,dimension))},('eq:implementation-parameter-preflight','eq:modulus-preflight'),())
